services:
  - type: web
    name: heu
    runtime: node
    plan: free
    region: frankfurt
    repo: https://github.com/tdi-rosa/heu
    branch: main
    buildCommand: npm ci --include=dev && npm run build && npm test
    startCommand: npm start
    healthCheckPath: /health
    autoDeployTrigger: commit
    envVars:
      - key: NODE_ENV
        value: production
